global_config:
  pipeline_name: core
  stage_promotions:
    dev: test
    test: prod
default_config:
  env: 
    env_type: dev
    label: null
    account: null
    region: us-west-2
default_config_overrides:
  dev:
    env: 
      env_type: dev
      account: ${CDK_DEFAULT_ACCOUNT} 
      region: ${CDK_DEFAULT_REGION}

